apiVersion: v1
kind: Service
metadata:
  labels:
    app: sowl-mautic 
  name: sowl-mautic 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sowl-mautic 
