kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sowl-dev
  namespace: sowl-dev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]