<?php namespace App\Doctrine;

use LaravelDoctrine\ORM\Auth\DoctrineUserProvider as Base;
use Illuminate\Contracts\Auth\Authenticatable;


class DoctrineUserProvider extends Base
{
    /**
     * Retrieve a user by their unique identifier.
     *
     * @param mixed $identifier
     *
     * @return Authenticatable|null
     */
    public function retrieveById($identifier)
    {
        $user = null;
        if ($identifier) {
            /** @var Authenticatable $user */
            $user = $this->getRepository()->find($identifier);
        }
        return $user;
    }

    public function retrieveByToken($identifier, $token)
    {
        return parent::retrieveByToken($identifier, $token); // TODO: Change the autogenerated stub
    }
}