apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: analytics.scholarshipowl.tech
  namespace: grafana
spec:
  secretName: analytics.scholarshipowl.tech
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
  - analytics.scholarshipowl.tech
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - analytics.scholarshipowl.tech