<h1>Scholarship Sweepstakes Official Rules</h1>
<h4>
    NO PURCHASE NECESSARY. A PURCHASE OR PAYMENT OF ANY KIND WILL NOT
    INCREASE YOUR CHANCES OF WINNING. VOID WHERE PROHIBITED BY LAW.
</h4>

<h3>Sweepstakes ID: {{ $scholarship['id'] }}</h3>

<p>
    {{ $business['name'] }}, a Delaware limited liability company (“Sponsor”), is
    pleased to offer the above-identified scholarship sweepstakes (“Sweepstakes”).
    As a condition of participating in the Sweepstakes, you agree to be fully and
    unconditionally bound by these Official Rules and the decisions of Sponsor,
    whose decisions shall be final and binding in all respects, and, the fullest
    extent provided by law, waive any right to claim ambiguity in the Sweepstakes,
    these Official Rules, Sweepstakes materials, and information contained on
    Sponsor’s website (the “Website”). The Sweepstakes is subject to applicable
    federal, state, and local laws and regulations and is VOID WHERE PROHIBITED
    OR RESTRICTED BY LAW. Winning and receiving a prize is contingent upon
    fulfilling all requirements set forth herein.
</p>

<h3>1. ELIGIBILITY</h3>
<p>
    The Sweepstakes is open only to citizens and permanent legal residents of the
    United States of America and that are physically located and residing therein
    who (i) are at least sixteen (16) years of age at the time of entry; (ii) are
    not barred from participation in the Sweepstakes under the laws of the
    United States, including but not limited to all federal, state, and local laws;
    (iii) are at the time of entry enrolled in or have been accepted into and will
    within six months of entry be enrolled in an accredited institution of
    post-secondary education; and (iv) at all times abide by these Official Rules.
    Individuals who are under the age of 18 at the time of entry must receive
    parental consent before entry. THE SWEEPSTAKES IS VOID WHERE PROHIBITED OR
    RESTRICTED BY LAW. ALL APPLICABLE FEDERAL, STATE AND LOCAL LAWS APPLY.
    Participant agrees to promptly provide any information requested by Sponsor to
    verify participant’s eligibility.
</p>
<p>
    Officers, directors, members, managers, employees, representatives, and agents
    of Sponsor and each of their respective parent companies, affiliates,
    subsidiaries, and any other companies associated with the design or execution
    of the Sweepstakes, including Immediate Family Members (as defined below) and
    Household Members (as defined below) for each of the aforementioned are not
    eligible to participate in or win the Sweepstakes. “Immediate Family Members”
    shall mean spouse, parents, step-parents, legal guardians, children,
    step-children, siblings or step-siblings and each of their spouses regardless
    of where they reside. “Household Members” shall mean those people who share
    the same residence at least three (3) months a year.
</p>

<h3>2. SWEEPSTAKES PERIOD</h3>
<p>
    The Sweepstakes begins on {{ $scholarship['start'] }} and ends on
    {{ $scholarship['deadline'] }} ("Sweepstakes Period"). {{ $scholarship['timezone'] }}
    shall control for all purposes of the Sweepstakes. Sponsor's computer shall be the
    official clock of the Sweepstakes.
</p>

<h3>3. HOW TO ENTER</h3>
<p>
    NO PURCHASE OR PAYMENT OF ANY KIND IS REQUIRED TO ENTER. A PURCHASE OR PAYMENT WILL
    NOT INCREASE YOUR CHANCES OF WINNING.
</p>
<p>
    During the Sweepstakes Period, eligible individuals may submit one (1) entry into
    the Sweepstakes by completing the Sweepstakes entry form located at
    <a href="{{ $scholarship['url'] }}">{{ $scholarship['url'] }}</a>.
</p>

<h3>4. ENTRY CONDITIONS</h3>
<p>
    There is a limit of one (1) entry per person. Subsequent attempts made by the same
    individual to submit multiple entries by using multiple or false contact or account
    information, or otherwise, may result in the entrant being disqualified, at Sponsor’s
    sole discretion. Entries generated by a script, computer programs, macro-programmed,
    robotic or any other automated means are void and may be disqualified at Sponsor’s sole
    discretion. Entries that are in excess of the stated limits, incomplete, incorrect,
    illegible, corrupted, damaged, destroyed, forged, false, lost, late, misdirected,
    deceptive, or are otherwise not in compliance with the Official Rules are also void
    and may be disqualified from the Sweepstakes at Sponsor’s sole discretion. Sponsor will
    not be responsible for invalid submissions and has no obligation to advise an individual
    of such a submission. If a problem occurs in the entry process, the entrant is solely
    responsible for verifying that the entry process has been validly completed.
</p>
<p>
    Entries received outside the Sweepstakes Period will not be included in the Sweepstakes.
    For purposes of this Sweepstakes, an entry is “received” when the Sponsor’s servers
    record the entry information. Screen shots, printouts or other purported "proof" or
    "evidence" of entry or winning, in lieu of Sponsor's validation process, shall not be
    binding. Proof of sending (such as an automated receipt, screen shots, etc.) does not
    constitute proof of actual receipt of an entry for purposes of these Official Rules.
</p>
<p>
    All entries become the sole and exclusive property of Sponsor and will not be acknowledged
    or returned. Any information provided by you or collected by Sponsor in connection with
    the Sweepstakes may be used by Sponsor in accordance with its online privacy policy
    available at <a href="{{ $scholarship['pp_url'] }}">{{ $scholarship['pp_url'] }}</a>.
</p>

<h3>5. PRIZES AND PRIZE RESTRICTIONS</h3>
<p>
    Subject to verification of eligibility and compliance with these Official Rules, the
    following prize will be awarded to the Sweepstakes’ winner:
</p>
<ul>
    <li>
        <p>
            <u>${{ $scholarship['amount'] }} Scholarship:</u>{{ $scholarship['awards'] }}
            winner will be chosen at random to win a ${{$scholarship['amount']}} scholarship.
            Scholarship will be paid by Sponsor directly to the winner within sixty (60) days
            of winner's compliance with these Official Rules. The winner agrees to only use
            the scholarship to pay for "qualified education expenses" as defined by the Internal
            Revenue Service in IRS Publication 970.
        </p>
        <p>
            <strong>A maximum of one (1) prize will be awarded.</strong>
        </p>
    </li>
</ul>
<p>
    Total ARV of all prizes that could be awarded in the Sweepstakes is ${{ $scholarship['amount'] }}.
    Prizes will be awarded only if the potential prize winner fully complies with these Official Rules.
    All prize details are at the sole discretion of Sponsor and any depiction of the prizes, in Sweepstakes
    materials or otherwise, is for illustrative purposes only. Prizes are non-transferable,
    non-exchangeable, and non-refundable, and must be accepted by the winner as awarded. A prize
    winner may waive his/her right to receive a prize. Sponsor shall have no responsibility or
    obligation to a prize winner or a potential prize winner who is unable or unavailable to, or
    who does not for any reason, accept or utilize a prize. In the event of non-compliance with
    these Official Rules, or if a prize is unclaimed (as determined by Sponsor in its sole discretion),
    that prize will be forfeited. A forfeited prize may be awarded to an alternate winner,
    in Sponsor's sole discretion.
</p>
<p>
    All federal, state, provincial and local taxes, and all costs and expenses related to the
    acceptance and use of a prize not specified herein, are the sole responsibility of the prize winner.
    Any required tax reporting forms will be furnished to the appropriate authorities.
</p>

<h3>6. WINNER NOTIFICATION AND VERIFICATION</h3>
<p>
    Sponsor will select a potential winner at random from all eligible Sweepstakes
    participants on {{ $scholarship['deadline'] }} (“Draw Date”). Sponsor will attempt
    to notify a potential winner using the email address and telephone number
    associated with their Sweepstakes submission within three (3) business days of the
    Draw Date. If a potential winner cannot be contacted or does not respond to
    Sponsor within seventy-two (72) hours of Sponsor’s initial notification, the
    potential winner may be disqualified at Sponsor’s sole discretion.
</p>
<p>
    A potential winner must provide Sponsor the information required to file any
    necessary tax reporting forms, including but not limited to their Social Security
    number or tax ID for tax reporting purposes if Sponsor is required to file an
    IRS Form 1099 with the Internal Revenue Service for the value of a prize awarded
    and accepted. Except where prohibited by law, a potential winner also may be
    required to sign and return to Sponsor, within seventy-two (72) hours of Sponsor’s
    initial notification, a Winner’s Affidavit and Publicity Release (“Affidavit”) via
    email to the address specified by Sponsor in order to claim his or her prize.
    If the potential winner is under the age of 18, the Affidavit must be co-signed by
    a parent or legal guardian. If the Affidavit is returned as undeliverable or
    incomplete or a potential winner fails to complete, sign and return the applicable
    Affidavit within the required time period, or the potential winner does not adhere
    to the Official Rules, including without limitation, the potential winner does not
    fulfill the eligibility requirements, the potential winner may be disqualified at
    Sponsor’s sole discretion.
</p>
<p>
    In the event a potential winner is disqualified for any reason, or if a prize is
    unclaimed or not accepted, the prize will be forfeited. If forfeited for any reason,
    the potential winner will not receive any other prize substitution or compensation,
    and the prize will remain the property of Sponsor and will not be awarded, except as
    provided herein. Sponsor, at its sole discretion, may award the forfeited prize to
    an alternate potential winner. If the Sponsor decides to select an alternate
    potential winner for the prize, the alternate will be selected at random from all
    eligible Sweepstakes participants and will be required to adhere to the timeframes
    and obligations of potential winners as stated in the previous paragraphs of this
    section 6. Sponsor retains the right to repeat this process until an alternate
    potential winner complies with these Official Rules.
</p>
<p>
    ALL POTENTIAL WINNERS ARE SUBJECT TO VERIFICATION BY SPONSOR. SPONSOR’S DECISIONS
    AS TO THE ADMINISTRATION AND OPERATION OF THE SWEEPSTAKES, ANY CHANGES TO THESE
    OFFICIAL RULES, AND THE SELECTION OF POTENTIAL WINNERS IS FINAL AND BINDING IN ALL
    MATTERS RELATED TO THE SWEEPSTAKES.
</p>

<h3>7. ODDS OF WINNING</h3>
<p>
    The odds of winning depend on the number of participants. Estimated odds of winning
    the prize are 1:10,000.
</p>

<h3>8. RIGHTS OF PUBLICITY</h3>
<p>
    Except where prohibited by law, by participating in this Sweepstakes or accepting
    a prize, you grant Sponsor and its designees to use and/or publish your full name,
    city and state of residence, photographs or other likenesses, pictures, portraits,
    video, voice, testimonials, biographical information (in whole or in part), and/or
    statements made by entrant regarding the Sweepstakes, Sponsor, worldwide and in
    perpetuity for any and all purposes, including, but not limited to, advertising,
    trade and/or promotion on behalf of Sponsor in any and all forms of media, now
    known or hereafter devised, including, but not limited to, print, TV, radio,
    electronic, cable, or World Wide Web, without further limitation, restriction,
    compensation, notice, review, or approval.
</p>
<p>
    YOU FURTHER ACKNOWLEDGE THAT YOUR PERSONAL IDENTIFYING INFORMATION MAY BE DISCLOSED
    TO THIRD PARTIES INCLUDING, WITHOUT LIMITATION, PLACING YOUR NAME ON A WINNERS’ LIST.
</p>

<h3>9. GENERAL CONDITIONS</h3>
<p>
    Winning a prize is contingent upon accepting these Official Rules and fulfilling all
    requirements of these Official Rules. Sponsor reserves the right without liability to
    disqualify any entrant or cancel, suspend, modify and/or terminate the Sweepstakes,
    or any part of it, for any reason, including, but not limited to, insufficient entries
    in the Sweepstakes, any printing, seeding, typographical, technical errors, human or
    otherwise, suspected or actual evidence of electronic or non-electronic tampering with
    any portion of the Sweepstakes, or if computer virus, bugs, unauthorized intervention,
    fraud, or technical difficulties or failures compromise or corrupt or affect the
    administration, integrity, security, fairness, or proper conduct of the Sweepstakes or
    any other factor beyond Sponsor’s reasonable control, as determined by Sponsor at its
    sole discretion. In such event, Sponsor reserves the right to award the prizes to the
    extent required by law for eligible entries submitted up to the time of the impairment
    (and/or thereafter), or in such other manner as deemed fair and appropriate by Sponsor
    at its sole discretion. Sponsor also reserves the right to disqualify any individual it
    finds to be tampering or interfering with the operation of the Sweepstakes, acting in
    violation of these Official Rules or in an unsportsmanlike or disruptive manner and
    void such individual’s entry.
</p>
<p>
    ANY ATTEMPT BY ANY PERSON TO DELIBERATELY UNDERMINE THE LEGITIMATE OPERATION OF THE
    SWEEPSTAKES MAY BE IN VIOLATION OF CRIMINAL AND CIVIL LAWS AND SHOULD SUCH AN ATTEMPT
    BE MADE, SPONSOR RESERVES THE RIGHT TO SEEK CIVIL AND/OR CRIMINAL PROSECUTION AND DAMAGES
    (INCLUDING ATTORNEYS’ FEES) FROM ANY SUCH PERSON TO THE FULLEST EXTENT PERMITTED BY LAW.
</p>
<p>
    The invalidity or unenforceability of any provision of these Official Rules will not
    affect the validity or enforceability of any other provision. In the event that any
    provision of the Official Rules is determined to be invalid or otherwise unenforceable
    or illegal, the other provisions will remain in effect and will be construed in accordance
    with their terms as if the invalid or illegal provision were not contained herein.
    Sponsor's failure to enforce any term of these Official Rules will not constitute a waiver
    of that provision. Headings are solely for convenience of reference and will not be deemed
    to affect in any manner the meaning or intent of the Official Rules or any provision hereof.
</p>

<h3>10. RELEASE AND LIMITATION OF LIABILITY</h3>
<p>
    By participating, you agree to release, indemnify, defend, and hold harmless Sponsor and
    each of its respective officers, directors, members, managers, employees, representatives,
    agents, successors and assigns as well as the Social Media Group (as defined in section 16)
    (collectively, the “Released Parties”) from and against any and all claims, expenses, and
    liability of any kind resulting or arising from the Sweepstakes (including reasonable
    attorneys’ fees), including, but not limited to, negligence and damages of any kind to
    persons and property, invasion of privacy (under appropriation, intrusion, public disclosure
    of private facts, false light in the public eye or any other legal theory), defamation,
    slander, libel, violation of right of publicity, infringement of trademark, copyright, or
    other intellectual property rights, property damage, or death or personal injury arising
    out of or relating to your entry, creation of an entry or submission of an entry,
    participation in the Sweepstakes, acceptance, use, or misuse of a prize, or the broadcast,
    exploitation, or use of an entry.
</p>
<p>
    To the maximum extent permitted by law, the Released Parties are not responsible for: (i)
    any incorrect or inaccurate information, whether caused by entrants, technical errors, or
    by any of the equipment or programming associated with or utilized in the Sweepstakes;
    (ii) technical failures of any kind, including, without limitation, malfunctions,
    interruptions, or disconnections of the equipment or software associated with or utilized
    in the Sweepstakes; (iii) unauthorized human and/or mechanical intervention in any part of
    the entry process or the Sweepstakes; (iv) technical or human error which may occur in the
    administration of the Sweepstakes or the processing of entries; or (v) any injury or damage
    to persons or property including, without limitation, death, bodily injury, pain and
    suffering, emotional distress or loss of data which may be caused, directly or indirectly,
    in whole or in part, from entrant’s participation in the Sweepstakes or receipt, use or
    misuse of any prize. If for any reason your entry is confirmed to have been erroneously
    deleted, lost, or otherwise destroyed or corrupted, your sole remedy is to submit another
    entry during the Sweepstakes Period through a method set forth in these Official Rules.
    Under no circumstances will you be permitted to obtain awards for, and you hereby waive
    all rights to claim punitive, incidental and consequential damages and any other damages,
    other than for actual out-of-pocket expenses, and any and all rights to have damages
    multiplied or otherwise increased.  Some jurisdictions do not allow the limitations or
    exclusion of liability for punitive, incidental or consequential damages, in which case the
    liability of the Released Parties will be limited to the maximum extent permitted by law.
</p>

<h3>11. PRIVACY</h3>
<p>
    By participating, you agree you will be sharing your personal information with Sponsor.
    You further agree to Sponsor’s collection, use and disclosure of your personal information
    in accordance with its respective online privacy policy, available at
    <a href="{{ $scholarship['pp_url'] }}">{{ $scholarship['pp_url'] }}</a>.
</p>

<h3>12. DISPUTES</h3>
<p>
    By participating, you agree that any and all disputes and claims arising out of or in
    connection with this Sweepstakes, or any prizes awarded, shall be resolved individually,
    without resort to any form of class or joint action. You further agree that if the dispute
    or claim is not otherwise resolved through direct discussions or mediation, it shall then
    be resolved by final and binding arbitration administered by the
    American Arbitration Association, in accordance with its rules for the resolution of
    consumer disputes ("AAA Rules") and applying Delaware law. You waive any right to bring
    your dispute or claim in court except as permitted by the AAA Rules. All proceedings brought
    pursuant to this section will be conducted in New York, New York. You further agree that,
    to the fullest extent permitted by law, (i) any and all claims, judgments, and awards shall
    be limited to actual out-of-pocket costs incurred, including costs associated with entering
    this Sweepstakes, and in no event will you be entitled to received attorneys’ fees or other
    legal costs; and (ii) under no circumstances will you be permitted to obtain awards for, and
    you hereby waive all rights to claim, punitive, incidental, and consequential damages, and
    any other damages, other than for actual out-of-pocket expenses, and any and all rights to
    have damages multiplied or otherwise increased.
</p>
<p>
    All issues and questions concerning the construction, validity, interpretation and
    enforceability of these Official Rules, or the rights and obligations of you and Sponsor in
    connection with this Sweepstakes, shall be governed by, and construed in accordance with the
    laws of the State of Delaware, without giving effect to any choice of law or conflict of law
    rules or provisions, and the forum and venue for any dispute shall be the state or federal
    courts in New York, New York.
</p>

<h3>13. EXTENDED MEANINGS; CURRENCY; FORCE MAJEURE</h3>
<p>
    Unless otherwise specified in these Official Rules, words importing the singular include the
    plural and vice versa and words importing gender include all genders. All dollar amounts
    referred to in these Official Rules are in lawful money of the United States of America.
    The Released Parties are not responsible for any damages caused by delay or failure to
    perform undertakings pursuant to these Official Rules when the delay or failure is due to
    weather, event cancellations, fires, strikes, floods, acts of God or the state’s enemies,
    lawful acts of public authorities, delays or defaults caused by common carriers, or other
    events that cannot reasonably be foreseen or provided against.
</p>

<h3>14. OFFICIAL RULES AND WINNERS' LIST</h3>
<p>
    These Official Rules are available at
    <a href="{{ $scholarship['url'] }}">{{ $scholarship['url'] }}</a>. The Sweepstakes Winners’ List
    will be available by sending a self-addressed stamped envelope to:
</p>
<p>
    <span>{{ $business['name'] }}</span><br/>
    <span>{{ $business['address'] }}</span>&nbsp;<span>{{ $business['address2'] }}</span><br/>
    <span>{{ $business['city'] }}, {{ $business['region'] }} {{ $business['zip'] }}</span><br/>
    <span>Attn: Winners' List</span><br/>
</p>
<p>
    Please include the Sweepstakes ID when requesting the Winners’ List. The Winners’ List will be
    available for three (3) months after the end of the Sweepstakes.
</p>

<h3>15. SPONSOR</h3>
<p>Sweepstakes is sponsored by:</p>
<p>
    <span>{{ $business['name'] }}</span><br/>
    <span>{{ $business['address'] }}</span>&nbsp;<span>{{ $business['address2'] }}</span><br/>
    <span>{{ $business['city'] }}, {{ $business['region'] }} {{ $business['zip'] }}</span><br/>
</p>

<h3>16. SOCIAL NETWORKING SITE DISCLAIMERS</h3>
<p>
    As a condition of participating in the Sweepstakes, you agree and acknowledge that Facebook Inc.,
    Instagram, LLC, Twitter, Inc. and any other social networking sites used to promote the
    Sweepstakes as well as their owners directors, officers, employees, contractors, agents,
    representatives, parents, subsidiaries, attorneys, insurers, and associated entities
    (collectively, the “Social Media Group”) are not sponsors of the Sweepstakes nor do they endorse
    or administer the Sweepstakes, nor are they in any way associated with the Sweepstakes. All
    questions regarding the Sweepstakes must be directed to Sponsor, not the Social Media Group.
    You also agree that as a condition of participating in the Sweepstakes, you shall release the
    Social Media Group from any and all liability arising out of or relating to your entry, creation
    of an entry or submission of an entry, participation in the Sweepstakes, acceptance, use, or
    misuse of any prize, or the broadcast, exploitation, or use of an entry. Please refer to each
    Social Media Group company’s respective privacy policy for important information regarding their
    collection, use and disclosure of personal information. This Sweepstakes is in no way sponsored,
    endorsed, administered by, or associated with Facebook Inc., Instagram, LLC or Twitter, Inc.
    Any and all questions, comments or complaints regarding the Sweepstakes must be directed only to
    Sponsor and not Facebook Inc., Instagram, LLC or Twitter, Inc.
</p>
