apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.nginx.name }}
  labels:
    app: {{ .Values.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.services.nginx.type }}
  ports:
    - name: {{ .Values.services.nginx.ports.http.name }}
      port: {{ .Values.services.nginx.ports.http.port }}
    - name: {{ .Values.services.nginx.ports.https.name }}
      port: {{ .Values.services.nginx.ports.https.port }}
  selector:
    app: {{ .Values.app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.phpfpm.name }}
  labels:
    app: {{ .Values.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.services.phpfpm.type }}
  ports:
    - port: {{ .Values.services.phpfpm.ports.port }}
  selector:
    app: {{ .Values.app  }}
