apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-test.go.sunrising.tech
  namespace: sunrise-dev
spec:
  secretName: wildcard-test.go.sunrising.tech
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.go.sunrising.tech'
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - '*.go.sunrising.tech'
