# Default values for scholarships.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app: sowl-dev
updateStrategy:
  type: RollingUpdate
replicaCount: 1

livenessProbe:
  exec:
    command:
    - cat
    - /var/www/html/healthy
  initialDelaySeconds: 50
  timeoutSeconds: 10
  failureThreshold: 5
readinessProbe:
  exec:
    command:
    - cat
    - /var/www/html/healthy
  initialDelaySeconds: 50
  timeoutSeconds: 10
  failureThreshold: 5

containers:
  nginx:
    name: nginx
    repository: gcr.io/sowl-tech/sowl-nginx/nginx
    tag: v8.2
    pullPolicy: IfNotPresent
    httpPort: 80
  phpfpm:
    name: php-fpm
    repository: gcr.io/sowl-tech/sowl-dev/php-fpm
    tag: v0.1
    pullPolicy: IfNotPresent
    port: 9000
service:
  name: lb
  type: NodePort
  externalPort: 8080
  internalPort: 80
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - @REPLACE_HOST
  annotations:
    kubernetes.io/ingress.class: "nginx-sowl"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  tls:
    # Secrets must be manually created in the namespace.
  - secretName: dev.scholarshipowl.tech
    #   hosts:
    #     - chart-example.local
resources: {}

nodeSelector:
  node: preemptible


volume:
  name: sowl-dev-volume
  path: /var/www/html

mysqlService: will-be-replaced

# MYSQL
mysql:
  mysqlDatabase: scholarship_owl
  mysqlUser: scholarship_owl
  mysqlPassword: Cs6ZQuaxwDLkhwL
  mysqlRootPassword: secret
  nodeSelector:
    node: preemptible
  configurationFiles:
    mysql.cnf: |-
      [mysqld]
      sql-mode=
      max_allowed_packet=500M