<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'install_source' => 'Docker',
	'db_host' => 'sunrise-mautic-gcloud-sqlproxy',
	'db_name' => 'mautic',
	'db_user' => 'mautic',
	'db_password' => '4&jv=Lhf!x@t#4,g{2`s',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.14-google-log',
	'mailer_from_name' => 'Sunrising.io',
	'mailer_from_email' => 'support@sunrising.io',
	'mailer_transport' => 'mautic.transport.sparkpost',
	'mailer_host' => 'mailhog.scholarshipowl.tech',
	'mailer_port' => '1025',
	'mailer_user' => null,
	'mailer_password' => 'a47774d328ccb7752c1ae7ec9569a6b80b33e078',
	'mailer_encryption' => null,
	'mailer_auth_mode' => 'login',
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '38d00d9dd59e3e3c99c950c0cd08df3e207959b7ce3d1fe5c80bc18c8e341a1e',
	'site_url' => 'http://engage.sunrising.io',
	'webroot' => null,
	'cache_path' => '/var/www/html/app/cache',
	'log_path' => '/var/www/html/app/logs',
	'image_path' => 'media/images',
	'tmp_path' => '/var/www/html/app/cache',
	'theme' => 'Mauve',
	'locale' => 'en_US',
	'dev_hosts' => null,
	'trusted_hosts' => array(

	),
	'trusted_proxies' => array(

	),
	'rememberme_key' => 'e46f0b4b3b95c75d97e34625d3383b13e28098fd',
	'rememberme_lifetime' => '31536000',
	'rememberme_path' => '/',
	'default_pagelimit' => 30,
	'default_timezone' => 'UTC',
	'date_format_full' => 'F j, Y g:i a T',
	'date_format_short' => 'D, M d',
	'date_format_dateonly' => 'F j, Y',
	'date_format_timeonly' => 'g:i a',
	'ip_lookup_service' => 'maxmind_download',
	'ip_lookup_auth' => null,
	'ip_lookup_config' => array(

	),
	'update_stability' => 'stable',
	'cookie_path' => '/',
	'cookie_secure' => null,
	'do_not_track_ips' => array(

	),
	'do_not_track_bots' => array(
		'0' => 'MSNBOT',
		'1' => 'msnbot-media',
		'2' => 'bingbot',
		'3' => 'Googlebot',
		'4' => 'Google Web Preview',
		'5' => 'Mediapartners-Google',
		'6' => 'Baiduspider',
		'7' => 'Ezooms',
		'8' => 'YahooSeeker',
		'9' => 'Slurp',
		'10' => 'AltaVista',
		'11' => 'AVSearch',
		'12' => 'Mercator',
		'13' => 'Scooter',
		'14' => 'InfoSeek',
		'15' => 'Ultraseek',
		'16' => 'Lycos',
		'17' => 'Wget',
		'18' => 'YandexBot',
		'19' => 'Java/1.4.1_04',
		'20' => 'SiteBot',
		'21' => 'Exabot',
		'22' => 'AhrefsBot',
		'23' => 'MJ12bot',
		'24' => 'NetSeer crawler',
		'25' => 'TurnitinBot',
		'26' => 'magpie-crawler',
		'27' => 'Nutch Crawler',
		'28' => 'CMS Crawler',
		'29' => 'rogerbot',
		'30' => 'Domnutch',
		'31' => 'ssearch_bot',
		'32' => 'XoviBot',
		'33' => 'digincore',
		'34' => 'fr-crawler',
		'35' => 'SeznamBot',
		'36' => 'Seznam screenshot-generator',
		'37' => 'Facebot',
		'38' => 'facebookexternalhit'
	),
	'do_not_track_internal_ips' => array(

	),
	'link_shortener_url' => null,
	'cached_data_timeout' => '10',
	'batch_sleep_time' => '1',
	'cors_restrict_domains' => 1,
	'cors_valid_domains' => array(

	),
	'rss_notification_url' => 'https://mautic.com/?feed=rss2&tag=notification',
	'max_entity_lock_time' => 0,
	'api_enabled' => 1,
	'api_enable_basic_auth' => false,
	'api_oauth2_access_token_lifetime' => 60,
	'api_oauth2_refresh_token_lifetime' => 14,
	'api_batch_max_limit' => '200',
	'upload_dir' => '/var/www/html/app/../media/files',
	'max_size' => '6',
	'allowed_extensions' => array(
		'0' => 'csv',
		'1' => 'doc',
		'2' => 'docx',
		'3' => 'epub',
		'4' => 'gif',
		'5' => 'jpg',
		'6' => 'jpeg',
		'7' => 'mpg',
		'8' => 'mpeg',
		'9' => 'mp3',
		'10' => 'odt',
		'11' => 'odp',
		'12' => 'ods',
		'13' => 'pdf',
		'14' => 'png',
		'15' => 'ppt',
		'16' => 'pptx',
		'17' => 'tif',
		'18' => 'tiff',
		'19' => 'txt',
		'20' => 'xls',
		'21' => 'xlsx',
		'22' => 'wav'
	),
	'campaign_time_wait_on_event_false' => 'PT1H',
	'mailer_return_path' => 'sunrise@bounces.sunrising.io',
	'mailer_append_tracking_pixel' => 1,
	'mailer_convert_embed_images' => 0,
	'mailer_amazon_region' => 'email-smtp.us-east-1.amazonaws.com',
	'mailer_custom_headers' => array(

	),
	'mailer_spool_msg_limit' => null,
	'mailer_spool_time_limit' => null,
	'mailer_spool_recover_timeout' => '900',
	'mailer_spool_clear_timeout' => '1800',
	'unsubscribe_text' => '<a href="|URL|">Unsubscribe</a> to no longer receive emails from us.',
	'webview_text' => '<a href="|URL|">Having trouble reading this email? Click here.</a>',
	'unsubscribe_message' => 'We are sorry to see you go! |EMAIL| will no longer receive emails from us. If this was by mistake, <a href="|URL|">click here to re-subscribe</a>.',
	'resubscribe_message' => '|EMAIL| has been re-subscribed. If this was by mistake, <a href="|URL|">click here to unsubscribe</a>.',
	'monitored_email' => array(
		'general' => array(
			'address' => '',
			'host' => '',
			'port' => '993',
			'encryption' => '/ssl',
			'user' => '',
			'password' => ''
		),
		'EmailBundle_bounces' => array(
			'address' => '',
			'host' => '',
			'port' => '993',
			'encryption' => '/ssl',
			'user' => '',
			'password' => '',
			'override_settings' => '0',
			'folder' => ''
		),
		'EmailBundle_unsubscribes' => array(
			'address' => '',
			'host' => '',
			'port' => '993',
			'encryption' => '/ssl',
			'user' => '',
			'password' => '',
			'override_settings' => '0',
			'folder' => ''
		),
		'EmailBundle_replies' => array(
			'address' => '',
			'host' => '',
			'port' => '993',
			'encryption' => '/ssl',
			'user' => '',
			'password' => '',
			'override_settings' => '0',
			'folder' => ''
		)
	),
	'mailer_is_owner' => 0,
	'default_signature_text' => 'Best regards, |FROM_NAME|',
	'email_frequency_number' => null,
	'email_frequency_time' => null,
	'show_contact_preferences' => 1,
	'show_contact_frequency' => 0,
	'show_contact_pause_dates' => 0,
	'show_contact_preferred_channels' => 0,
	'show_contact_categories' => 0,
	'show_contact_segments' => 0,
	'mailer_mailjet_sandbox' => 0,
	'mailer_mailjet_sandbox_default_mail' => null,
	'disable_trackable_urls' => 0,
	'parallel_import_limit' => '1',
	'background_import_if_more_rows_than' => 0,
	'cat_in_page_url' => 0,
	'google_analytics' => null,
	'track_contact_by_ip' => 0,
	'track_by_tracking_url' => 0,
	'track_by_fingerprint' => 0,
	'facebook_pixel_id' => null,
	'facebook_pixel_trackingpage_enabled' => 0,
	'facebook_pixel_landingpage_enabled' => 0,
	'google_analytics_id' => null,
	'google_analytics_trackingpage_enabled' => 0,
	'google_analytics_landingpage_enabled' => 0,
	'rabbitmq_host' => 'localhost',
	'rabbitmq_port' => '5672',
	'rabbitmq_vhost' => '/',
	'rabbitmq_user' => 'guest',
	'rabbitmq_password' => 'guest',
	'beanstalkd_host' => 'localhost',
	'beanstalkd_port' => '11300',
	'beanstalkd_timeout' => '60',
	'sms_username' => null,
	'sms_password' => null,
	'sms_sending_phone_number' => null,
	'sms_frequency_number' => null,
	'sms_frequency_time' => null,
	'sms_transport' => 'mautic.sms.transport.twilio',
	'saml_idp_entity_id' => 'http://engage.sunrising.io',
	'saml_idp_own_password' => null,
	'saml_idp_email_attribute' => 'EmailAddress',
	'saml_idp_username_attribute' => null,
	'saml_idp_firstname_attribute' => 'FirstName',
	'saml_idp_lastname_attribute' => 'LastName',
	'saml_idp_default_role' => 1,
	'webhook_start' => '0',
	'webhook_limit' => '10',
	'webhook_log_max' => '1000',
	'webhook_disable_limit' => '100',
	'webhook_timeout' => '15',
	'queue_mode' => 'immediate_process',
	'events_orderby_dir' => 'ASC',
	'twitter_handle_field' => 'twitter',
	'mailer_api_key' => 'afee2ad6c665e25403a49395344b40d571e557c6',
	'google_analytics_anonymize_ip' => 0,
	'saml_idp_metadata' => 'PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxtZDpFbnRpdHlEZXNjcmlwdG9yIHhtbG5zOm1kPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bWV0YWRhdGEiIGVudGl0eUlEPSJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9zYW1sMj9pZHBpZD1DMDNlYWQ1YWEiIHZhbGlkVW50aWw9IjIwMjMtMDctMThUMTU6NTI6NTguMDAwWiI+CiAgPG1kOklEUFNTT0Rlc2NyaXB0b3IgV2FudEF1dGhuUmVxdWVzdHNTaWduZWQ9ImZhbHNlIiBwcm90b2NvbFN1cHBvcnRFbnVtZXJhdGlvbj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIj4KICAgIDxtZDpLZXlEZXNjcmlwdG9yIHVzZT0ic2lnbmluZyI+CiAgICAgIDxkczpLZXlJbmZvIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj4KICAgICAgICA8ZHM6WDUwOURhdGE+CiAgICAgICAgICA8ZHM6WDUwOUNlcnRpZmljYXRlPk1JSURkRENDQWx5Z0F3SUJBZ0lHQVdTelBwRzhNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1Ic3hGREFTQmdOVkJBb1RDMGR2YjJkc1pTQkoKYm1NdU1SWXdGQVlEVlFRSEV3MU5iM1Z1ZEdGcGJpQldhV1YzTVE4d0RRWURWUVFERXdaSGIyOW5iR1V4R0RBV0JnTlZCQXNURDBkdgpiMmRzWlNCR2IzSWdWMjl5YXpFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V3SGhjTk1UZ3dOekU1Ck1UVTFNalU0V2hjTk1qTXdOekU0TVRVMU1qVTRXakI3TVJRd0VnWURWUVFLRXd0SGIyOW5iR1VnU1c1akxqRVdNQlFHQTFVRUJ4TU4KVFc5MWJuUmhhVzRnVm1sbGR6RVBNQTBHQTFVRUF4TUdSMjl2WjJ4bE1SZ3dGZ1lEVlFRTEV3OUhiMjluYkdVZ1JtOXlJRmR2Y21zeApDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJRXdwRFlXeHBabTl5Ym1saE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXk1NklaZjdCN2NoYVlPd0xjekhRRVNyd3hNMXFDL1VGc3NWNENnQ0xYNXVZRUN0WVloYWNKQ3dDYnBaeWxVbk8Kbld0ejhoZFQ1cnpHVnZqUURaS2p2VlkvZ2FKbkx5VmFYak12TWVMUWtacC9sczJpU0JlRmd0dUZSQWN6NlJwZTNMeFg2SkRQMUl2eApWQVNDbTFEcDBLK0RDVmdaTGYvbkNDcmRycktpcWFRVFNvVkJGajd6bzkxUWNLcXM1S1F3RTBqMG90OTl5dU8yRVlSUkN6Z0wrUUxJCkVmSk5hVGdUcFBISk82Y29sdS9CazlKNVZQYjc0THNUNDFhZlR1bTJ2NlVjOHF0ZmZ5MmlRNjFLZFBiK3k3QTZjbGRnTDFSaDZrKzcKUzhTeDRZUzhUQ29JYzlxYjJ2TW9jN0E5ZEUyZnJrcURvUEJ1U01XWFkzQkI0cmZRS1FJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCUjFpSVh6Si8zbk9IN2YwN0VMTTlFdXgxRm5KbFlNT0pLUjFKZWFiTDZXNGF1TzRDUit5b1NMenFmWDBlSEl2aWVTY2dkCk5WNmI3S2pDQVlSU2ZtTmNXT0o2Yno5N1hPNWlFRU5Kell1bytJL09BZnNtZ2NibldnNEZFVzBic2lqZ2RlQkhRYTE0VU1ud281RWoKVVFKT0xUN3JZdkY5djRwSjYwZ0hjakpqeFk3MllJSnY0UHBVV0wvemV3eDErbzQyeWw0SWRWdTlwcGk1UjRJL1FoQmpkNjVpWDd0MQpMVE9URmdtMjgwNUVwbWduc0o1OElEZnNxQTBvNHBpSHJaaVJHTnUyR2tQQzVlbVdvYjUyZHo3a0ZydFhxT0VEa1YxVjUrNk94Vkx4Cmt1WXZLRlVnd2h4bXozRXY4OE5tbEozKzlhalJWZG04YzJIajZQaEtrcVV5PC9kczpYNTA5Q2VydGlmaWNhdGU+CiAgICAgICAgPC9kczpYNTA5RGF0YT4KICAgICAgPC9kczpLZXlJbmZvPgogICAgPC9tZDpLZXlEZXNjcmlwdG9yPgogICAgPG1kOktleURlc2NyaXB0b3IgdXNlPSJzaWduaW5nIj4KICAgICAgPGRzOktleUluZm8geG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPgogICAgICAgIDxkczpYNTA5RGF0YT4KICAgICAgICAgIDxkczpYNTA5Q2VydGlmaWNhdGU+TUlJRGREQ0NBbHlnQXdJQkFnSUdBV2VFdW95S01BMEdDU3FHU0liM0RRRUJDd1VBTUhzeEZEQVNCZ05WQkFvVEMwZHZiMmRzWlNCSgpibU11TVJZd0ZBWURWUVFIRXcxTmIzVnVkR0ZwYmlCV2FXVjNNUTh3RFFZRFZRUURFd1pIYjI5bmJHVXhHREFXQmdOVkJBc1REMGR2CmIyZHNaU0JHYjNJZ1YyOXlhekVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXdIaGNOTVRneE1qQTIKTVRneE5ETTNXaGNOTWpNeE1qQTFNVGd4TkRNM1dqQjdNUlF3RWdZRFZRUUtFd3RIYjI5bmJHVWdTVzVqTGpFV01CUUdBMVVFQnhNTgpUVzkxYm5SaGFXNGdWbWxsZHpFUE1BMEdBMVVFQXhNR1IyOXZaMnhsTVJnd0ZnWURWUVFMRXc5SGIyOW5iR1VnUm05eUlGZHZjbXN4CkN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BEWVd4cFptOXlibWxoTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBeTFyM0hqellqeGlRM3o2RmVtUE81TExCcmZSbHB2TVFWK1JwcFNjSS9zeDFpTWZBdVdtb1Q5ZnlyOG53WHNsUwpKTmFkNGJBeCsxQklUYk5MKzRKL09zc2pSNkQ2Qnh1dWpiUndOYUQ5dFJxOHp3TGg2UnVnbFRjc1VVS2M4bnNjU0FBeTVLMGlIaUlGCm56V2JYTnRoWUZsZmpsM0svYWRhVnhOYjBSSzFxSlpOdWJ4aDFISHA3elZITWtvVGdwYTRUQWpkdU1lZjlvU2JucjBKTnR3ME9wcFQKVFovazhGcDltWElMRGRjbGNqOTBTYjNFNEdFS2l1L1ByMkZLaGh3NjRNVExNeTh0U2tQR05VKzFOV2xyM3Vvd3g5L0gvYXpmSjJyMQp5TGxuMk5ZdWw2SkJLSzhMOVQ4NlhoYWkzWHpubEVhZGNhcyt5Q1hpT0pvbC9lZDljd0lEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBCkE0SUJBUUJNQmhVME9VamMxVkdpWHViOWVZSzZUTlVsOWJzVy94V3piaXMwdzQ1MkQ3c0ZEZkVVNkp1UWwvTUMrWlhIbFdVdHN4bi8KQXRGREFmTklMV0RnRi9LeVN3WjRsY1Y2c1ljV1lLWFBPbElGck1nQzNzZUFlSlorcXVLTGZROFJhTUdYak9HMHJ2Sy9MOHVPdGNBVApyYk9Ubm5VdTcwQXBpVTEwQWg3SldKUUJjRDRLaVNnS2VVejVBWFhTb0d1am9VOUpIc3hzLzdxMUg4TTdMbEMrU2RJampmaTdkbmhMCjlkUEJoVzdVb0ViY3Q2b3lvYm5JRDFVc0tXdW8yUVhsN0JIWDNFd0ZFMVg2dVZrOEI4N3kzcysrRndEemJDdisrdnp2Qk9DcUY0MjQKQ05tck5XVysxUTNQY0NSNVV1S015N1B1Njk5OE9YMmk3Z1hCNFJyWW90SGY8L2RzOlg1MDlDZXJ0aWZpY2F0ZT4KICAgICAgICA8L2RzOlg1MDlEYXRhPgogICAgICA8L2RzOktleUluZm8+CiAgICA8L21kOktleURlc2NyaXB0b3I+CiAgICA8bWQ6TmFtZUlERm9ybWF0PnVybjpvYXNpczpuYW1lczp0YzpTQU1MOjEuMTpuYW1laWQtZm9ybWF0OmVtYWlsQWRkcmVzczwvbWQ6TmFtZUlERm9ybWF0PgogICAgPG1kOlNpbmdsZVNpZ25PblNlcnZpY2UgQmluZGluZz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmJpbmRpbmdzOkhUVFAtUmVkaXJlY3QiIExvY2F0aW9uPSJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9zYW1sMi9pZHA/aWRwaWQ9QzAzZWFkNWFhIi8+CiAgICA8bWQ6U2luZ2xlU2lnbk9uU2VydmljZSBCaW5kaW5nPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YmluZGluZ3M6SFRUUC1QT1NUIiBMb2NhdGlvbj0iaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vc2FtbDIvaWRwP2lkcGlkPUMwM2VhZDVhYSIvPgogIDwvbWQ6SURQU1NPRGVzY3JpcHRvcj4KPC9tZDpFbnRpdHlEZXNjcmlwdG9yPg==',
	'saml_idp_own_certificate' => null,
);
