apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress.scholarshipowl.com
  namespace: ingress-nginx
spec:
  secretName: ingress.scholarshipowl.com
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
  - ingress.scholarshipowl.com
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - ingress.scholarshipowl.com