type: object
properties:
  id:
    type: integer
  accountId:
    type: integer
  requirementTextId:
    type: integer
  accountFile:
    $ref: "AccountFile.yml"
  text:
    type: string
  createdAt:
    $ref: "DateObject.yml"
  updatedAt:
    $ref: "DateObject.yml"
  scholarshipId:
    type: integer

