# Default values for revive.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app: revive-new
updateStrategy:
  type: RollingUpdate
volume:
  revive:
    name: revive-volume
    path: /var/www/html
    size: 10Gi
    accessMode: ReadWriteOnce

livenessProbe:
  httpGet:
    path: /
    port: 80
  timeoutSeconds: 15
  initialDelaySeconds: 15
readinessProbe:
  httpGet:
    path: /
    port: 80
  timeoutSeconds: 15
  initialDelaySeconds: 15

# CONTAINERS
containers:
# Nginx container
  nginx:
    name: nginx
    replicaCount: 1
    port: 80
    image:
      repository: gcr.io/sowl-marketing/revive/nginx
      tag: v1.6
      pullPolicy: IfNotPresent
# Php-fpm container
  phpfpm:
    name: php-fpm
    replicaCount: 1
    port: 9000
    image:
      repository: gcr.io/sowl-marketing/revive/php-fpm
      tag: v0.1
      pullPolicy: IfNotPresent

service:
  name: lb
  type: NodePort
  externalPort: 8080
  internalPort: 80

services:
# Nginx service
  nginx:
    name: lb
    type: NodePort
    ports:
      http:
        name: http
        port: 80
      https:
        name: https
        port: 443
# Php-fpm service
  phpfpm:
    name: revive-php-fpm
    type: NodePort
    ports:
      port: 9000
# Ingress service
  ingress:
    enabled: true
    # Used to create an Ingress record.
    hosts:
      - revive.new.scholarshipowl.com
    annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
    - secretName: revive.new.scholarshipowl.com
      hosts:
       - revive.new.scholarshipowl.com

mysql:
  imageTag: 5.7
  mysqlDatabase: revive
  mysqlUser: revive
  mysqlPassword: t0QfRjhIk3sPTXF
  persistence:
    enabled: true
    existingClaim: revive-mysql
resources: {}