apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: apply.me
  namespace: applyme-dev
spec:
  secretName: apply.me
  issuerRef:
    name: sowl-marketing-prod
    kind: ClusterIssuer
  dnsNames:
    - dev.stg.apply.me
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - dev.stg.apply.me