apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: app.sunrising.io
  namespace: sunrise
spec:
  secretName: sunrising.io
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
    - app.sunrising.io
  acme:
    config:
    - http01:
         ingressClass: nginx
      domains:
      - app.sunrising.io