apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sunrise.test.dev.scholarshipowl.com
  namespace: sunrise-test
spec:
  secretName: sunrise.test.dev.scholarshipowl.com
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
  - sunrise.test.dev.scholarshipowl.com
  acme:
    config:
    - http01:
         ingressClass: nginx
      domains:
      - sunrise.test.dev.scholarshipowl.com