apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: revive.scholarshipowl.com
  namespace: revive
spec:
  secretName: revive.scholarshipowl.com
  issuerRef:
    name: sowl-marketing-prod
    kind: ClusterIssuer
  commonName: 'revive.scholarshipowl.com'
  dnsNames:
    - 'revive.scholarshipowl.com'
  acme:
    config:
    - dns01:
         provider: prod-cloudflare
      domains:
      - 'revive.scholarshipowl.com'
