apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: engage.scholarship.app
  namespace: sunrise-mautic
spec:
  secretName: engage.scholarship.app
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  commonName: 'engage.scholarship.app'
  dnsNames:
    - 'engage.scholarship.app'
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - 'engage.scholarship.app'
