apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.app }}-app
  labels:
    app: {{ .Values.app }}
    chart: {{ template "sunrise-mautic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.app }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MAUTIC_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sunrise-mautic-mysql-secret
                  key: host
            - name: MAUTIC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: sunrise-mautic-mysql-secret
                  key: user
            - name: MAUTIC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sunrise-mautic-mysql-secret
                  key: password
            - name: MAUTIC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: sunrise-mautic-mysql-secret
                  key: db_name
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html
            name: mautic-sunrise-home
            readOnly: false
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      volumes:
       - name: mautic-sunrise-home
         persistentVolumeClaim:
          claimName: sunrise-mautic-pvc-2
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
