kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sunrise-mautic-pvc-2
  namespace: sunrise-mautic
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "100Gi"
