@extends('base')

@php $metaData = 'Terms of Use'; @endphp
@section('metatitle')
    <title>{{ $metaData }}</title>
    <meta property="og:title" content="{{ $metaData }}" />
    <meta name="twitter:title" content="{{ $metaData }}" />
@endsection

@section("metatags")
    <meta name="description" content="{{ $metaData }}" />
    <meta name="keyword" content="{{ \CMS::keywords() }}" />
    <meta name="author" content="{{ \CMS::author() }}" />
    <meta property="og:image" content="{{ url('assets/img/mascot.png') }}"  />
    <meta property="og:description" content="{{ $metaData }}" />
    <meta name="twitter:image" content="{{ url('assets/img/mascot.png') }}" />
    <meta name="twitter:description" content="{{ $metaData }}" />
@endsection

@section("scripts2")
    @if(Auth::user())
    {!! \App\Extensions\AssetsHelper::getJSBundle('user') !!}
    @endif
    {!! \App\Extensions\AssetsHelper::getJSBundle('login') !!}
    {!! \App\Extensions\AssetsHelper::getJSBundle('main') !!}
@endsection

    @section('content')

    <!-- Terms of Use header -->
    <div class="blue-bg clearfix">
      <div class="container">
        <div class="row">
          <div class="text-container text-white text-center">
            <h1 class="page-title text-large text-light">Terms of Use</h1>
          </div>
        </div>
      </div>
    </div>

    <!-- Terms of Use body -->
    <div class="section--terms-and-conditions paleBlue-bg clearfix">
      <div class="container">
        <div class="row">
          <div class="text-container">
            <h3>
              <strong>ScholarshipOwl &ndash; Terms of Use</strong>
            </h3>
            <p>Last updated: September 2019 </p>
            <p>These Terms of Use contains the terms and conditions that govern your access to and use of the Services (as defined below) to be provided to you by <span></span> (&ldquo;<strong>Owl</strong>&rdquo;) and is an agreement between Owl and you (&ldquo;<strong>Customer</strong>&rdquo;). These Terms of Use takes effect when you click or check the applicable button or box associated with these Terms of Use or, if earlier, when you use any of the Services (&ldquo;<strong>Effective Date</strong>&rdquo;). </p>
            <p><strong>Owl may update these Terms of Use from time to time and will notify Customer of such updates either via email or by posting notice of such changes on its website, or other reasonable means. Customer&rsquo;s continued use of the Services after Owl&rsquo;s provision of a notice of an updated version of these Terms of Use shall constitute Customer&rsquo;s consent to such updated Terms of Use.</strong></p>
            <h2 class="h4"><p><strong>1. </strong><strong>Terms of Service.</strong></p></h2>
            <p><strong>1.1</strong> <u>Access and Use of Services</u>. </p>
            <p>Customer may access and use the <strong>scholarship management interface technology and services</strong> offered by Owl on its web site at <a href="http://scholarshipowl.com"><span><u>http://scholarshipowl.com</u></a> (<strong>&ldquo;Website&rdquo;</strong>) to which Customer has subscribed or agreed to accept (<strong>&ldquo;Services&rdquo;</strong>), in accordance with these Terms of Use. </span></p>
            <p>Without limiting the foregoing, the permission granted to Customer to access and use the Services is based on Customer&rsquo;s agreement to not access or use the Services for: (i) developing a product or service that could reasonably be regarded as being competitive with the Services, or (ii) monitoring the availability, performance or functionality of the Services, or for any other benchmarking or competitive purpose. </p>
            <p><strong>Customer shall not, and shall not permit third parties to, block, mask or obscure advertisements that appear on the Website.</strong> </p>
            <p><strong>1.2</strong> <u>No Double Registration</u>. Owl will provide Customer with the opportunity to reject individual scholarship providers. Customer agrees to reject any scholarship provider to which Customer or anyone on Customer&rsquo;s behalf has applied in the past. Customer acknowledges that any failure to reject duplicative applications may disqualify Customer&rsquo;s other applications, and Customer hereby waives all claims against Owl relating to such disqualification. </p>
            <p><strong>1.3</strong> <u>Additional Services</u>. Owl may from time to time offer additional services (&ldquo;<strong>Additional Services</strong>&rdquo;). If Customer chooses to accept or purchase Additional Services, Customer may be required to enter into a specific agreement for such Additional Services (&ldquo;<strong>Additional Agreement</strong>&rdquo;), provided that the terms of these Terms of Use will continue to apply to such Addition Services unless specifically amended by or conflicting with the terms of such Additional Agreement. Unless otherwise provided, the term &ldquo;Services&rdquo; shall include the Additional Services. </p>
            <p>The Official Rules attached hereto as <strong>Exhibit A</strong> constitute an Additional Agreement for Owl&rsquo;s scholarship sweepstakes Additional Services, and Customer agrees to such Official Rules. </p>
            <p><strong>1.4</strong> <u>Customer Account</u>. To access the Services, Customer must create an account associated with a valid email address (&ldquo;<strong>Account</strong>&rdquo;). When Customer signs up for the Services, Owl shall create a dedicated email address on behalf of Customer with <a href="http://www.scholarshipowl.com"><span><u>scholarshipowl.com</u></a> (&ldquo;<strong>Owl Email Address</strong>&rdquo;). Customer is solely responsible for Customer&rsquo;s Account, including for: (i) controlling the access to, and use and security of, the Account and Customer&rsquo;s Content (as defined below), (ii) maintaining the security of the passwords and other measures used to protect access to the Account, and (iii) all instructions provided to Owl through the Account, whether or not authorized by Customer. Owl is not responsible for unauthorized access to the Account. Customer will contact Owl immediately if Customer believes an unauthorized third party may be using the Account. Nothing in the foregoing requires Owl to monitor the Account for unauthorized access or any other security breach. </span></p>
            <p>&ldquo;<strong>Customer&rsquo;s Content&rdquo;</strong> shall mean any information Customer has provided or has been collected in connection with establishing the Account or using the Services.</p>
            <p><strong>1.5</strong> <u>Separate Services</u><u>;</u><u> Disclaimer</u>. Owl may from time to time advertise to Customer, either through the Services or through a separate correspondence to Customer, third party services or offers that are not included as part of the Services, such as services offered by third-party scholarship providers (<strong>&ldquo;Separate Services&rdquo;</strong>). Customer hereby provides its affirmative consent to receive offers for Separate Services through email, such consent which may be withdrawn at any time at Customer&rsquo;s discretion by sending an email to <span><u><a href="mailto:unsubscribe@scholarshipowl.com">unsubscribe@scholarshipowl.com</a></u>. Customer hereby agrees to review all terms of service and other agreements related to all Separate Services. Customer shall be solely responsible for strict compliance with any such terms of service or other agreements and for any liability arising from Customer&rsquo;s use of the Separate Services. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THESE TERMS OF USE, OWL MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE SEPARATE SERVICES AND SHALL NOT BE RESPONSIBLE FOR ANY DAMAGES CAUSED BY THE SEPARATE SERVICES, INCLUDING WITHOUT LIMITATION ANY DAMAGES ARISING OUT OF ANY MISREPRESENTATIONS OR VIOLATIONS OF LAW. OWL’S ADVERTISEMENT OF ANY SEPARATE SERVICE DOES NOT CONSTITUTE AN ENDORSEMENT OF THE SEPARATE SERVICE. </span></p>
            <p><strong>1.6</strong> <u>Third Party Services</u>. Certain components of the Services may be comprised of third party services (&ldquo;<strong>Third Party Services</strong>&rdquo;), and Owl may perform its obligations hereunder through the third party providers of such Third Party Services (&ldquo;<strong>Third Party Service Providers</strong>&rdquo;). Without restricting the limitation of liability and disclaimer of warranty provisions of these Terms of Use, Owl shall be responsible to Customer for Third Party Services to no greater extent than the same extent as such Third Party Service Providers are liable to Owl for provision of the Third Party Services. Owl may at any time, in its sole discretion, replace its Third Party Service Providers. </p>
            <p><strong>1.7</strong> <u>Services Changes</u>. Owl may change or discontinue any of the Services or change or remove features or functionality of the Services from time to time, without any liability to Customer. Owl will use commercially reasonable efforts to notify Customer of any material change to or discontinuation of the Services. </p>
            <p><strong>1.8</strong> <u>Suspension of Services</u>. At any time, Owl may suspend the provision of Services and remove any of Customer&rsquo;s Content transmitted via the Services without liability: (i) if Owl believes that any Service is being used in violation of these Terms of Use or applicable law, (ii) if Owl believes that the use of the Services may pose a security risk to Owl or any third party, (iii) if ordered by a law enforcement or government agency or otherwise in order to comply with applicable law, (iv) if necessary for operation, maintenance or expansion of Owl&rsquo;s Services, or for other technological purposes, (v) if required or requested by a Third Party Service Provider or if the Third Party Service is suspended or ceases to be provided for any reason (whether generally or through Owl), or (vi) if Customer fails to fulfill payment obligations. To the extent practicable, Owl shall use commercially reasonable efforts to notify Customer prior to suspending Services, except that no notice is required prior to suspension due to not fulfilling payment obligations. Account information will be unavailable to Customer during a suspension of Services. </p>
            <p><strong>1.9</strong> <u><a href="/privacy" target="_blank">Privacy Policy</a></u><u>; </u><u><a href="/terms" target="_blank">Site Terms</a></u>. Customer consents to the collection, use and disclosure of information associated with Customer and Customer's use of the Website and the Services in accordance with these Terms of Use and the <span><u><a href="/privacy" target="_blank">Owl Privacy Policy</a></u>; all as may be updated from time to time. </span></p>
            <h2 class="h4"><p><strong>2. Fees &amp; </strong><strong>Billing.</strong></p></h2>
            <p><strong>2.1</strong> <u>Fees</u>. </p>
            <p>In consideration for Customer&rsquo;s usage of the Services, Customer agrees to pay Owl fees at Owl&rsquo;s then-current pricing for the Services as published from time to time on the Website. All payments from Customer to Owl must be in United States Dollars.</p>
            <p>Owl may in its sole discretion modify its pricing upon the provision of at least 30 days&rsquo; notice to already-paying customers, by posting a notice on the Website and sending an email to the address maintained for the relevant Account.</p> <p>Unless Customer notifies Owl in writing of Customer&rsquo;s termination of its use of the Services within 14 days after delivery of such notice, the Customer will be deemed to have consented to the updated pricing.</p>
            <p><strong>2.2</strong> <u>Billing.</u></p>
            <p>Owl will bill Customer’s credit card / debit card / PayPal account for the Services ordered by Customer, either as a one-time payment, or in automatically reoccurring payments if Customer has an ongoing subscription. Owl shall send a sales receipt to Customer upon request.</p>
            <p> Customers with ongoing subscriptions are responsible for maintaining current and complete credit card / debit card / PayPal account information on file with Owl’s payment processor at all times. Owl uses Braintree (a PayPal service) as its payment processor. Customers’ payment account information, including credit/debit card number or PayPal account information, are stored by Braintree and may be used for future or reoccurring payments (if the Customer has an ongoing subscription with reoccurring payments). Changes to on-file payment account information, or requests to delete payment account information on file, must be communicated to Owl at <a href="mailto:scholarships@scholarshipowl.com">scholarships@scholarshipowl.com</a>. Owl may change its payment processor at any time with or without notice to Customer. </p>
            <p> All charges are automatically made on Customer’s specific billing cycle date as disclosed during the enrollment process. If Customer’s Services begin with a free trial period, Customer must cancel the Services prior to the end of the free trial period in order to avoid being charged. </p>
            <p>Owl shall have the right to suspend Customer’s Account without prior notice once payment is overdue by 10 calendar days.</p>
            <p> TO THE FULLEST EXTENT PERMITTED BY LAW, CUSTOMER WAIVES ALL CLAIMS RELATING TO CHARGES ASSOCIATED WITH THE SERVICES UNLESS CLAIMED WITHIN SIXTY (60) DAYS AFTER THE CHARGE.</p>
            <p><strong>2.3</strong> <u>Cancellation</u>. Subject to the requirements of Section 3 below, Customer may cancel their Services by (i) submitting a cancellation request through their Account on the Website; (ii) sending an email to <a href="mailto:scholarships@scholarshipowl.com">scholarships@scholarshipowl.com</a> specifying the email address used for the account and clearly indicating that they want to cancel or (iiI) calling customer service at 800 494 4908 Monday - Friday, 11a.m. to 6p.m. EST and 8a.m. to 3p.m. PST.</p>
            <p><strong>2.4</strong> <u>Refunds</u>. Except as specifically identified in this Section 2.3, all payments to Owl are non-refundable.  If Customer purchased a Service that began with a free trial period and does not cancel prior to the end of the free trial period, (i) the first fee paid following the free trial period is non-refundable and (ii) subsequent fees are non-refundable except that Owl will refund upon request the fee paid for the most recent billing cycle so long as Customer has not logged into or otherwise accessed or used the Service during the applicable billing cycle.  If Customer purchased a Service that did not begin with a free trial period, fees are non-refundable except that Owl will refund upon request the fee paid for the most recent billing cycle so long as Customer has not logged into or otherwise accessed or used the Service during the applicable billing cycle.  To request a refund, Customer must submit their request using Owl’s contact form, sending an email to refunds@scholarshipowl.com, or calling 1-800-494-4908.</p>
            <p><strong>2.5</strong> <u>Late Fees</u>. Owl may charge interest on overdue amounts at the lesser of 1.5% per month or the maximum rate permitted by law, plus all reasonable expenses and costs of collection (including collection agency fees, attorney fees and court costs). The assessment of interest shall not limit Owl&rsquo;s other rights and remedies for late payment, including Owl&rsquo;s right to suspend or terminate access to the Services. </p>
            <p><strong>2.6</strong> <u>Taxes</u>. Customer is responsible for all taxes, fees and duties, including penalties and interest, imposed in connection with these Terms of Use and the Services (<strong>&ldquo;Taxes&rdquo;</strong>). Customer will pay Owl its fees without reduction for Taxes. If Owl is obligated to collect or pay Taxes, the Taxes will be invoiced to Customer, unless Customer provides Owl on a timely basis with a valid tax exemption certificate authorized by the appropriate taxing authority (along with any supporting documentation that Owl may require in connection with such tax exemption certificate). If any deduction or withholding is required by law, Customer will notify Owl and pay Owl any additional amounts necessary to ensure that the net amount that Owl receives, after any deduction and withholding, equals the amount Owl would have received if no deduction or withholding has been required. Customer shall provide to Owl original or certified copies of all Tax payments or other evidence of payment of Taxes by Customer with respect to transactions or payments under these Terms of Use. </p>
            <p><strong>2.7</strong> <u>Third Party Fees</u>. Any third party fees (including credit card, debit card, PayPal and bank fees) (&ldquo;<strong>Third Party Fees</strong>&rdquo;) are Customer&rsquo;s sole responsibility, and if charged to Owl, Customer shall pay Owl an additional amount equaling the Third Party Fees in order to ensure that the net amount that Owl receives equals the amount Owl would have received if no Third Party Fees had been charged. </p>
            <h2 class="h4"><p><strong>3. </strong><strong>Term and Termination.</strong></p></h2>
            <p><strong>3.1</strong> <u>Term</u>. These Terms of Use will commence on the Effective Date and will remain in effect until terminated by either party in accordance with the terms hereof. Customer is encouraged to keep records of all communications regarding termination.</p>
            <p><strong>3.2</strong> <u>Termination for Convenience</u>. Each party may terminate these Terms of Use and Customer&rsquo;s right to access and use the Services by providing the other party with 7 business days prior notice. </p>
            <p>Customer&rsquo;s mere cancelation of its credit card / debit card / PayPal account associated with its Account does not terminate these Terms of Use or Customer&rsquo;s obligation to pay for the Services. In such case, Owl will continue to the Account as active and the billing cycle will continue, resulting in a past due account that may be turned over to a third party collection service.</p>
            <p><strong>3.3</strong> <u>Termination for Breach and Other Reasons</u>. Owl may terminate these Terms of Use and Customer&rsquo;s right to access and use the Services immediately and without liability upon providing notice to Customer as follows: (i) if Owl suspects a breach of these Terms of Use or violation of applicable law, (ii) if Owl is threatened with a legal claim, including for intellectual property infringement, related to the Services, (iii) if Customer&rsquo;s act or omission results in a suspension described in Section 1.8, (iv) if Owl&rsquo;s relationship with a Third Party Services Provider expires, terminates or requires Owl to change the Services or terminate these Terms of Use, (v) if Owl believes providing the Services could create an economic or technical burden or security risk, (vi) in order to comply with applicable law or requests of governmental entities, or (vii) if Owl determines that the use of the Services by Customer or Owl&rsquo;s provision of any of the Services has become impractical or unfeasible for any legal or regulatory reason. </p>
            <p><strong>3.4</strong> <u>Effect of Termination</u>. If these Terms of Use is terminated, then: (i) Owl shall immediately terminate Customer&rsquo;s access to the Services, including removing Customer from any scholarship sweepstakes in which Customer is enrolled as of the date of termination, (ii) all fees and Taxes that Customer is obliged to pay Owl, up to the effective date of termination, will be charged at the end of the then-current billing period, (iii) there will be no refund of any amount already paid by Customer as of the effective date of termination, including any amount in respect of the period following the effective date of termination, and (iv) Owl shall maintain Customer&rsquo;s Content. </p>
            <h2 class="h4"><p><strong>4. </strong><strong>Acceptable Use.</strong></p></h2>
            <p><strong>4.1</strong> Customer shall use the Services in compliance with all applicable laws, ordinances, rules and regulations, shall not violate or attempt to violate Owl&rsquo;s system or network security, and shall not misuse the Services in any way. Customer shall not (i) engage in, solicit, or promote any activity that is illegal, invasive, violates the rights of others, or could subject Owl to liability to third parties, (ii) submit Customer&rsquo;s Content that is defamatory, misleading, fraudulent, obscene, distasteful, harassing, discriminatory, racially or ethnically offensive, contains sexually suggestive or explicit content, facilitates or promotes illegal activity, or contains illegal content, (iii) distribute viruses, worms, Trojan horses, corrupted files, hoaxes, or other items of a disabling, destructive, damaging, or deceptive nature, or (iii) disable, interfere with, or circumvent any aspect of the Services. </p>
            <p><strong>4.2</strong> Owl may, but is not obligated to, monitor Customer&rsquo;s Content, and it is Customer&rsquo;s sole responsibility to monitor the content uploaded by Customer or on Customer's behalf, pursuant to the provisions of this Section 4. In the event there is concern regarding any violation of these Terms of Use by Customer, Owl is authorized, in its sole discretion, to monitor Customer&rsquo;s compliance, to immediately terminate or suspend the provision of Services to Customer, or to block the transmission of Customer&rsquo;s Content which in Owl&rsquo;s opinion violates these Terms of Use, any applicable law or otherwise may impose any liability on Owl. </p>
            <h2 class="h4"><p><strong>5.</strong> <strong>Publicity.</strong></p></h2>
            <p>Customer hereby irrevocably and in perpetuity grants to Owl, those acting under Owl&rsquo;s authority, and any third party sponsor or co-sponsor of a scholarship (&ldquo;<strong>Scholarship Partner</strong>&rdquo;) the unrestricted, absolute, perpetual, worldwide right and license to use Customer&rsquo;s name, address, photograph, likeness, voice, biographical and personal information, statements, Scholarship Sweepstakes application, essays, and any photograph, film, video, audio recording or other recording taken of Customer or such materials (collectively, &ldquo;<strong>Promotional</strong> <strong>Content</strong>&rdquo;), and all in connection with marketing purposes; and to reproduce, copy, modify, create derivative works of, display, perform, exhibit, distribute, transmit or broadcast, publicly or otherwise, or otherwise use and permit to be used, the Promotional Content or any part thereof, whether alone or in combination with other materials (including but not limited to text, data, images, photographs, illustrations, and graphics, video or audio segments of any nature), in any media whatsoever, in connection with such marketing purposes; and all the foregoing without any compensation, royalties, remuneration or consideration to Customer or to any third party, and Customer hereby waives all claims to compensation, royalties, remuneration, consideration, notice or permission in connection therewith. </p>
            <h2 class="h4"><p><strong>6. Customer&rsquo;s </strong><strong>Warranties.</strong></p></h2>
            <p>Customer represents and warrants to Owl that (i) Customer&rsquo;s Content is complete and accurate (besides being a breach of the terms of these Terms of Use, should Customer&rsquo;s Content not be complete and accurate, any application that Owl may submit on Customer&rsquo;s behalf may be unsuccessful or discarded, and incorrect Customer&rsquo;s Content may not be able to be later corrected), (ii) Customer has the requisite power and authority to enter into these Terms of Use and into any Additional Agreement, and to perform all of Customer&rsquo;s obligations hereunder, (iii) Customer is a natural person over the age of 13, and (iv) Customer is not named on any U.S. Government denied party list. Customer shall update Customer&rsquo;s Account information to maintain the accuracy of Customer&rsquo;s Content during the term of these Terms of Use. </p>
            <h2 class="h4"><p><strong>7. </strong><strong>Indemnification.</strong></p></h2>
            <p>Customer will defend, indemnify, and hold harmless Owl, its affiliates and licensors, and each of their respective employees, officers, directors, agents and representatives, from and against any claims, damages, losses, liabilities, costs, fines and expenses (including reasonable attorneys&rsquo; fees) arising out of or relating to: (i) Customer&rsquo;s actual or alleged use of the Services (including any activities under Customer&rsquo;s Account), (ii) breach of these Terms of Use, any Additional Agreement, any representation or warranty of Customer (including breach of any terms of use or agreement with any provider of Separate Services) or any violation of applicable law, or (iii) Customer&rsquo;s Content, including any claim involving alleged infringement or misappropriation of third-party rights by or in connection with Customer&rsquo;s Content. </p>
            <p>Owl shall promptly notify Customer of any claim subject to indemnification, provided that Owl&rsquo;s failure to do so shall not affect Customer&rsquo;s obligations hereunder, except to the extent that Owl&rsquo;s failure to promptly notify Customer materially delays or prejudices Customer&rsquo;s ability to defend the claim. At Owl&rsquo;s option, Customer will have the right to defend against any such claim with counsel of Customer&rsquo;s own choosing (subject to Owl&rsquo;s written consent) and to settle such claim as Customer deems appropriate, provided that Customer shall not enter into any settlement without Owl&rsquo;s prior written consent and provided that Owl may, at any time, elect to take over control of the defense and settlement of the claim. </p>
            <h2 class="h4"><p><strong>8. </strong><strong>Disclaimers of Warranties and Limitation of Liability.</strong></p></h2>
            <p><strong>8.1</strong> <u>Disclaimer of Warranties</u>. NOTWITHSTANDING ANY OTHER PROVISION IN THESE TERMS OF USE, ANY ADDITIONAL AGREEMENT OR OWL&rsquo;S PRIVACY POLICY,  TO THE FULLEST EXTENT PERMITTED BY LAW, THE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. OWL AND ITS AFFILIATES MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND (EXPRESS, IMPLIED, STATUTORY OR OTHERWISE) REGARDING THE SERVICES, ADDITIONAL SERVICES, THIRD PARTY SERVICES, OR SEPARATE SERVICES (COLLECTIVELY, &ldquo;<strong>ACCUMULATED SERVICES</strong>&rdquo;), INCLUDING ANY WARRANTY THAT THE ACCUMULATED SERVICES WILL BE UNINTERRUPTED, ERROR FREE OR FREE OF HARMFUL COMPONENTS, THAT ANY CONTENT, INCLUDING CUSTOMER&rsquo;S CONTENT OR THIRD PARTY CONTENT, WILL BE SECURE OR NOT OTHERWISE LOST OR DAMAGED, OR THAT THERE WILL NOT BE ANY TYPOGRAPHICAL OR OTHER ERRORS IN APPLICATIONS. OWL DOES NOT GUARANTEE THE RECEIPT OF ANY SCHOLARSHIP, AND CUSTOMER WAIVES ANY CLAIM AGAINST OWL IN CONNECTION THEREWITH, EVEN IF CUSTOMER WAS OTHERWISE ENTITLED TO SUCH SCHOLARSHIP. TO THE FULLEST EXTENT PERMITTED BY LAW, OWL AND ITS AFFILIATES HEREBY DISCLAIM ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, AND WARRANTIES ARISING OUT OF THE COURSE OF DEALING OR USAGE OF TRADE. CUSTOMER ACKNOWLEDGES THAT THERE ARE RISKS INHERENT IN INTERNET CONNECTIVITY AND THE SCHOLARSHIP MANAGEMENT INTERFACE TECHNOLOGY THAT COULD RESULT IN THE LOSS OF CUSTOMER&rsquo;S CONTENT, PRIVACY, DATA, CONFIDENTIAL INFORMATION, AND PROPERTY. </p>
            <p><strong>8.2</strong> <u>Limitation of Liability</u>. NOTWITHSTANDING ANY OTHER PROVISION IN THESE TERMS OF USE, ANY ADDITIONAL AGREEMENT OR OWL&rsquo;S PRIVACY POLICY, TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL OWL OR ANY OF ITS AFFILIATES, OR ANY OF THEIR EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, OR SUPPLIERS, BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (COLLECTIVELY &ldquo;<strong>DAMAGES</strong>&rdquo;), HOWEVER CAUSED AND UNDER ANY THEORY OF LAW (INCLUDING BREACH OF CONTRACT, TORT, STRICT LIABILITY, AND INFRINGEMENT), EVEN IF ADVISED OF THE POSSIBILITY OF DAMAGES AND EVEN IF DAMAGES ARE FORESEEABLE. THIS LIMITATION OF LIABILITY INCLUDES BUT IS NOT LIMITED TO, THE FOLLOWING DAMAGES: (A) CUSTOMER&rsquo;S INABILITY TO USE ANY OF THE ACCUMULATED SERVICES, INCLUDING AS A RESULT OF ANY (I) TERMINATION OR SUSPENSION OF THESE TERMS OF USE OR CUSTOMER&rsquo;S USE OF OR ACCESS TO THE SERVICES, (II) OWL&rsquo;S DISCONTINUATION OF ANY OF THE SERVICES, OR (III) DOWNTIME, INCLUDING ANY UNANTICIPATED OR UNSCHEDULED DOWNTIME OF ALL OR A PORTION OF THE SERVICES FOR ANY REASON, INCLUDING AS A RESULT OF ERRORS IN THE SCHOLARSHIP MANAGEMENT INTERFACE TECHNOLOGY, POWER OUTAGES, SYSTEM FAILURES OR OTHER INTERRUPTIONS, (B) THE COST OF OR TIME INVOLVED IN THE PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, (C) ANY INVESTMENTS, EXPENDITURES, LOST OPPORTUNITIES, OR COMMITMENTS BY CUSTOMER IN CONNECTION WITH THESE TERMS OF USE OR ANY ADDITIONAL AGREEMENT OR CUSTOMER&rsquo;S USE OF OR ACCESS TO THE ACCUMULATED SERVICES, AND (D) ANY UNAUTHORIZED ACCESS TO, ALTERATION OF, OR THE DELETION, DESTRUCTION, DAMAGE, LOSS OR FAILURE TO STORE ANY OF CUSTOMER&rsquo;S CONTENT. </p>
            <p>NOTWITHSTANDING ANY OTHER PROVISION IN THESE TERMS OF USE, ANY ADDITIONAL AGREEMENT OR OWL&rsquo;S PRIVACY POLICY, TO THE FULLEST EXTENT PERMITTED BY LAW, THE MAXIMUM AGGREGATE LIABILITY OF OWL OR ANY OF ITS AFFILIATES, OR ANY OF THEIR EMPLOYEES, OFFICERS, DIRECTORS, AGENTS OR SUPPLIERS, UNDER ANY THEORY OF LAW (INCLUDING FOR BREACH OF CONTRACT, TORT, STRICT LIABILITY, OR INFRINGEMENT), SHALL NOT EXCEED THE AMOUNT OF FEES ACTUALLY RECEIVED BY OWL FROM CUSTOMER FOR THE SIX MONTHS IMMEDIATELY PRECEDING THE FIRST CLAIM UNDER THESE TERMS OF USE OR ANY ADDITIONAL AGREEMENT. THIS IS AN AGGREGATE LIMIT. THE EXISTENCE OF MORE THAN ONE CLAIM SHALL NOT ENLARGE THIS LIMIT. </p>
            <p>CUSTOMER ACKNOWLEDGES THAT THE FOREGOING DISCLAIMERS OF WARRANTIES AND LIMITATIONS OF LIABILITY ARE ESSENTIAL PARTS OF THESE TERMS OF USE AND ABSENT SUCH DISCLAIMERS AND LIMITATIONS OWL WOULD NOT AGREE TO PROVIDE ANY SERVICES TO CUSTOMER OR ENTER INTO THESE TERMS OF USE OR ANY ADDITIONAL AGREEMENT. </p>
            <p>THE LAWS OF CERTAIN JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF SUCH LAWS APPLY TO CUSTOMER, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY, AND CUSTOMER MAY HAVE ADDITIONAL RIGHTS. </p>
            <h2 class="h4"><p><strong>9. </strong><strong>Proprietary Rights and Confidentiality.</strong></p></h2>
            <p><strong>9.1</strong> <u>Customer's</u><u> Content</u>. As between Owl and Customer, Customer owns all right, title and interest in and to Customer&rsquo;s Content. </p>
            <p><strong>9.2</strong> <u>Services</u>. As between Owl and Customer, Owl or its licensors own and reserve all rights, title and interest in and to the Services, Owl&rsquo;s trademarks, logos and service marks and all modifications to any of the forgoing and all related intellectual property rights, including, without limitation, all content accessible from the Website (other than Customer&rsquo;s Content), whether registered or not and whether registerable or not. Customer is required to retain all copyright, trademark and other notices on any copies Customer makes of the Website or any content contained therein. </p>
            <p><strong>9.3</strong> <u>Suggestions</u>. Should Customer provide Owl with any suggestions or ideas pertaining to the Services (&ldquo;<strong>Suggestions</strong>&rdquo;), Owl will own all right, title and interest in and to the Suggestions and will be free to use the Suggestions for any purpose without any liability or payment to Customer. Customer hereby irrevocably assigns to Owl all right, title and interest in and to Suggestions and agrees to provide Owl with reasonable assistance, at Owl&rsquo;s cost, required or desirable in order to document, perfect and maintain Owl&rsquo;s rights in the Suggestions. </p>
            <p><strong>9</strong><strong>.4</strong> <u>Confidentiality</u>. Customer agrees not to use any Confidential Information of Owl except in connection with Customer&rsquo;s authorized use of the Services. &ldquo;<strong>Confidential Information</strong>&rdquo; means all non-public information disclosed by Owl to Customer in connection with the Services, that Customer should reasonably understand to be confidential, including all non-public aspects of the Services. </p>
            <p><strong>9.5</strong> <u>Links to Website</u>.  Customer may link to the Website by using a text link and linking to the Website homepage or any other webpage or content contained on the Website, provided that the link Customer creates and the pages that are activated by the link do not: (i) duplicate Website content, (ii) frame or create a border around Website content or any pages on the Website, or use other techniques that alter in any way the visual presentation or appearance of any content on the Website, (iii) misrepresent your relationship with us or otherwise create a false affiliation, connection or association with us, (iv) imply that we approve or endorse Customer, Customer’s website or the content contained thereon, or Customer’s goods or services, (v) present false or misleading impressions regarding Owl or otherwise damage any goodwill associated with Owl’s name, Website, scholarships, other goods or services, or trademarks, (vi) use Owl’s trademarks in page text, metatags or hidden text in order to gain higher rankings from search engines, or (vii) use Owl’s name, trademarks, or Customer’s relationship with Owl, in a promotional manner without Owl’s prior written permission.</p>
            <h2 class="h4"><p><strong>10.</strong> <strong>Governing Law</strong><strong> &amp;</strong><strong> Jurisdiction.</strong> </p></h2>
            <p>These Terms of Use will be governed by and construed in accordance with the United States law without giving effect to any conflicts of laws provisions that would require the application of the laws of any other jurisdiction. The parties hereby expressly reject any application to these Terms of Use of: (i) the United Nations Convention on Contracts for the International Sale of Goods, and (ii) the 1974 Convention on the Limitation Period in the International Sale of Goods, as amended. All disputes arising out of these Terms of Use will be subject to the exclusive jurisdiction of the competent courts located in Delaware law in New Castle county, USA, and the parties agree and submit to the personal and exclusive jurisdiction and venue of these courts, except that nothing will prohibit Owl from instituting an action in any court of competent jurisdiction to obtain injunctive relief or protect or enforce its intellectual property rights or to otherwise protect its interests in the Services. </p>
            <h2 class="h4"><p><strong>11. Miscellaneous.</strong></p></h2>
            <p><strong>11.1</strong> <u>Non-Waiver</u>. A party&rsquo;s failure or delay in enforcing any provision of these Terms of Use will not be deemed a waiver of that party&rsquo;s rights with respect to that provision or any other provision of these Terms of Use. A party&rsquo;s waiver of any of its rights under these Terms of Use is not a waiver of any of its other rights with respect to a prior, contemporaneous or future occurrence, whether similar in nature or not. </p>
            <p><strong>11.2</strong> <u>Construction</u>. The headings in these Terms of Use are not part of these Terms of Use but are solely for the convenience of the parties. As used herein, the words &ldquo;include&rdquo; and &ldquo;including&rdquo; and variations thereof, will not be deemed to be terms of limitation, but rather will be deemed to be followed by the words &ldquo;without limitation.&rdquo; All references in these Terms of Use to &ldquo;Sections&rdquo; refer to sections herein. </p>
            <p><strong>11.3</strong> <u>Survival</u>. The terms of the following Sections shall survive any expiration or termination of these Terms of Use: 1.3 [Additional Services], 1.5 [Separate Services], 1.9 [Privacy Policy, Site Terms], 2 [Fees &amp; Billing], 3 [Term and Termination], 5 [Publicity], 7 [Indemnification], 8 [Disclaimers of Warranties and Limitation of Liability], 9 [Proprietary Rights and Confidentiality], 10 [Governing Law &amp; Jurisdiction] and 11 [Miscellaneous]. </p>
            <p><strong>11.4</strong> <u>Force Majeure</u>. Neither party shall be in default of any obligation under these Terms of Use if the failure to perform the obligation is due to any event beyond that party&rsquo;s reasonable control, including electrical or internet failure, natural disaster, war, riot, insurrection, epidemic, strikes or other organized labor action, terrorist activity, or events of a magnitude or type for which precautions are not generally taken in the industry. </p>
            <p><strong>11.5</strong> <u>Severability</u>. If any provision of these Terms of Use is held to be unenforceable for any reason, in whole or in part, such decision shall not affect the validity or enforceability of any or all of the remaining portions thereof. Any such unenforceable provision or portion thereof shall be changed and interpreted so as to best accomplish the objectives of such provision or portion thereof within the limits of applicable law. </p>
            <p><strong>11.6</strong> <u>Assignment</u>. Customer may not assign these Terms of Use without the prior written consent of Owl. </p>
            <p><strong>11.7</strong> <u>Notices</u>. Owl may provide notice of changes to these Terms of Use to Customer either via e-mail or by posting a notice of such changes on Owl&rsquo;s web site. Customer may provide notice to Owl by courier, mail or e-mail, provided that receipt of such notice is verified in writing by Owl. Owl can be reached at <a href="mailto:scholarships@scholarshipowl.com"><span><u>scholarships@scholarshipowl.com</u></a>, or at <span>{{ company_details()->getCompanyName() }}</span>, <span>{{ company_details()->getAddress1() }}</span></span>.</p>
            <p><strong>11.8</strong> <u>Entire Agreement</u>. These Terms of Use, along with Owl&rsquo;s other policies (including its privacy policy) and terms referenced herein, are the complete and exclusive agreement between the parties regarding its subject matter herein and supersedes and replaces any other written or oral agreement, understanding or communication regarding such subject matter. </p>
            <p id="exhibit" class="text-center h4"><u><strong>EXHIBIT A</strong></u></p>
            <p><u>Sweepstakes Official Rules</u></p>
            <p>Owl is pleased to offer the You Deserve it Scholarship Sweepstakes (&ldquo;<strong>Scholarship Sweepstakes</strong>&rdquo;) in which you can apply for a chance to win a scholarship to be used for tuition or books at your qualified high school, college or university within the United States (collectively, &ldquo;<strong>School</strong>&rdquo;). </p>
            <p><strong>NO PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR WIN THE SCHOLARSHIP SWEEPSTAKES. ANY PURCHASE, PAYMENT OR UPGRADE WILL NOT INCREASE YOUR CHANCES OF WINNING. THE SCHOLARSHIP SWEEPSTAKES IS VOID WHERE PROHIBITED OR RESTRICTED BY LAW. PLEASE SEE &ldquo;RESTRICTIONS&rdquo; BELOW.</strong></p>
            <p><strong>By applying to enter the Scholarship Sweepstakes, whether automatically by Owl upon your registration to the Website, or else by you actively applying to enter the Sweepstakes, you agree to be bound by these Official Rules, and you understand that any violation of these Official Rules shall result in your disqualification from the Scholarship Sweepstakes. All of Owl&rsquo;s decisions regarding the Scholarship Sweepstakes, including without limitation the selection of the winner, shall be final and binding in all respects. Owl reserves the right to amend or discontinue the Scholarship Sweepstakes and these Official Rules at any time in its sole discretion.</strong></p>
            <p><strong>The provisions set forth in the relevant Owl sweepstakes page </strong><strong> <b>&ldquo;<a href="https://scholarshipowl.com/awards/you-deserve-it-scholarship" target="_blank">Sweepstakes Page</a>&rdquo;</b> shall be deemed an integral part of these Official Rules. All capitalized terms not otherwise defined herein shall have the meaning ascribed to them on the Sweepstakes Page.</strong></p>
            <p><u>Eligibility</u></p>
            <p>You may apply to enter the Sweepstakes for a chance to win a scholarship for your School only if you meet the Eligibility Requirements set forth on the Sweepstakes Page. </p>
            <p>Owl reserves the right to disqualify any applicant from the Scholarship Sweepstakes at any time, and in its sole discretion.</p>
            <p>Without limiting the foregoing, you may not be an officer, director, member or employee of Owl or any other party associated with the development or administration of the Scholarship Sweepstakes, or an immediate family member (i.e., parents, children, siblings or spouse) of any of the foregoing, or a person living in the household of any of these individuals, whether or not related. </p>
            <p><u>How to Enter </u></p>
            <p>The Scholarship Sweepstakes will run for the Sweepstakes Period, as set forth on the Sweepstakes Page. </p>
            <p>Instructions for registration for the Sweepstakes Scholarship are set forth on the Sweepstakes Page. </p>
            <p>You may apply to enter the Scholarship Sweepstakes under a single name and a single email address. After the end of the Sweepstakes Period no further applications will be accepted. </p>
            <p>The estimated odds of winning are set forth on the Sweepstakes Page. Actual odds of winning depend upon the total number of eligible applications received. Each eligible application will have an equal chance of winning. </p>
            <p>Owl shall disqualify any applicant tampering with the application process or the operation of the Website, including without limitation through the use of bots or other automated processes to enter.</p>
            <p>All information you provide must be correct and complete.</p>
            <p>The Scholarship Sweepstakes is subject to applicable law, and is void where prohibited or restricted by law.</p>
            <p><u>Winner Selection</u></p>
            <p>Owl owns and operates several scholarship promotional websites and concurrently runs several scholarship promotional sweepstakes. On or around the Draw Date, as set forth on the Sweepstakes Page, Owl will hold a single scholarship promotional sweepstakes, where all eligible applicants from all of Owl&rsquo;s scholarship promotional websites and scholarship promotional sweepstakes will be combined, including eligible applicants for the Scholarship Sweepstakes, and a single winner of the Prize, as set forth on the Sweepstakes Page, will be selected by a random drawing of all such scholarship promotional sweepstakes, including the Scholarship Sweepstakes (&ldquo;<strong>Winner</strong>&rdquo;). </p>
            <p>In the event of a dispute regarding the identity of an applicant, including without limitation Winner, identity shall be deemed to be that of the natural person over 13 years of age owning the email address associated with the Winner&rsquo;s Account, as of the date that Owl receives such applicant&rsquo;s application for the Scholarship Sweepstakes.</p>
            <p><u>Prize</u></p>
            <p>The amount of the Prize is set forth on the Sweepstakes Page, and shall be used solely and exclusively for the full or partial payment of Winner&rsquo;s tuition and/or books at Winner&rsquo;s School. </p>
            <p>Owl shall either pay the amount of the Prize to Winner, or else directly to Winner&rsquo;s School, and all in Owl&rsquo;s sole discretion. </p>
            <p>Upon Owl&rsquo;s request, and prior to Winner being awarded the Prize, Winner agrees to provide Owl with proof of Winner&rsquo;s enrolment at the School and Winner&rsquo;s tuition bill, and any other information requested by Owl. </p>
            <p><u>Winner Notification</u></p>
            <p>Winner will be notified by e-mail or by telephone within approximately five (5) business days of the Draw Date, to be followed by written notification to Winner&rsquo;s Owl Email Address. </p>
            <p>Winner will be deemed to have forfeited the Prize, and an alternate applicant from all of Owl&rsquo;s scholarship promotional websites and scholarship promotional sweepstakes will be selected as the new single Winner by a random drawing in Winner&rsquo;s place, in the event of any of the following: (i) Winner cannot be contacted after reasonable efforts within three (3) business days after the first attempt to contact Winner, (ii) Winner chooses not to accept the Prize, or (ii) Winner does not comply with requirements from Winner set forth in these Official Rules (including on the Sweepstakes Page).&nbsp; </p>
            <p><u>Affidavit</u></p>
            <p>If requested by Owl, as a condition to winning the Prize Winner shall execute an <a><span><u><a href="/affidavit.pdf" target="_blank">&ldquo;Affidavit of Eligibility and Liability/Publicity Release&rdquo;</a></u></a> (&ldquo;<strong>Affidavit</strong>&rdquo;). Agreement to the publicity release portion of the Affidavit is not required for Tennessee residents. Where Winner is a minor, Winner&rsquo;s parent or legal guardian shall also execute the Affidavit.</span></p>
            <p><u>Verification of Information</u></p>
            <p>Although information that you provide may be verified, Owl is not under any obligation to verify any of the information that you provide, and you hereby warrant that all information that you provide in connection with the Scholarship Sweepstakes is complete and accurate.</p>
            <p><u>Ownership Of Applications</u></p>
            <p>All applications shall become the property of Owl and will not be returned. </p>
            <p><u>Taxes</u></p>
            <p>Without der limiting Section 2.5 of the Terms of Use, all taxes, costs and expenses associated with the receipt and/or use of the Prize shall be the sole and exclusive responsibility of the Winner and Winner shall report the value of any Prize for tax purposes as required by law. Without limiting the foregoing, Winner shall provide Owl with a completed Form W-9 with valid identification and a valid taxpayer identification number or social security number before the Prize will be awarded. If Winner wins over $600.00 in Prizes which are paid directly to Winner rather than being sent directly to the School or paid into a 529&nbsp;plan, then Winner will file a Form 1099 at the end of the relevant calendar year with the IRS. </p>
            <p><u>Official Rules, Decisions</u></p>
            <p>By entering the Scholarship Sweepstakes, you agree to be bound by these Official Rules and the decisions of Owl, which will be final and binding. Without limiting the foregoing, you agree that any violation of these Official Rules will result in your disqualification from the Scholarship Sweepstakes. <br> </p>
            <p><u>Disclaimer of Warranties, Limitation of Liability, and Privacy</u></p>
            <p>For the avoidance of doubt, and as set forth in Section 1.3 of the Terms of Use (&ldquo;Additional Services&rdquo;), without limitation both Section 1.9 of the Terms of Use (&rdquo;Privacy Policy, Site Terms&rdquo;), and Section 8 of the Terms of Use (&rdquo;Disclaimer of Warranties and Limitation of Liability&rdquo;) shall apply to these Official Rules. NOTWITHSTANDING ANY OTHER PROVISION IN THESE TERMS OF USE, ANY ADDITIONAL AGREEMENT OR OWL&rsquo;S PRIVACY POLICY, ALL CAUSES OF ACTION ARISING OUT OF OR CONNECTED WITH THE SCHOLARSHIP SWEEPSTAKES, INCLUDING WITHOUT LIMITATION IN CONNECTION WITH ANY APPLICATION OR PRIZE, SHALL BE RESOLVED INDIVIDUALLY WITHOUT RESORT TO ANY FORM OF CLASS ACTION, AND, TO THE FULLEST EXTENT PERMITTED BY LAW, IN ANY CAUSE OF ACTION THE SWEEPSTAKES ENTITIES&rsquo; MAXIMUM AGGREGATE LIABILITY SHALL BE LIMITED TO APPLICANT&rsquo;S DIRECT COSTS OF ENTERING AND PARTICIPATING IN THE SCHOLARSHIP SWEEPSTAKES. <span style="text-transform: uppercase">Each party shall be responsible for paying its own attorneys’ fees, costs and expenses, regardless of which party prevails, but a party may recover any or all of its attorneys’ fees, costs and expenses from another party if the court, applying applicable law, so determines</span>.</p>
            <p><u>Applicable Law and Jurisdiction</u></p>
            <p>The Scholarship Sweepstakes is subject to all applicable laws and regulations. Disputes concerning the construction, validity, interpretation or enforceability of these Official Rules shall be governed by the state laws of the Delaware law in New Castle county, without application of its conflict of laws principles. </p>
            <p><u>Restrictions: Non-Transferability, Right to Cancel, Suspend, or Modify</u></p>
            <p>Prizes are non-transferable and must be accepted as awarded. Owl reserves the right to cancel, suspend, or modify the Scholarship Sweepstakes and award the Prize from among all eligible applications received prior to such cancelation, suspension or modification, or to elect not to award the Prize at all, for any legal, commercial, technical or other event, and all in Owl&rsquo;s sole discretion. </p>
            <p><u>Winner List</u></p>
            <p>Names of Winners will be posted on Owl&rsquo;s Winners Page, and may be posted on the websites of Scholarship Partners or elsewhere, according to Owl&rsquo;s sole discretion. You may request a Winners&rsquo; list by sending a stamped, self-addressed envelope no later than ninety (90) days after the relevant Draw Date to: Owl, Winners&rsquo; List, <span>{{ company_details()->getAddress1() }}</span>.<br> </p>
            <p><u>Sponsor, No Affiliation Or Endorsement</u></p>
            <p>This promotion is sponsored solely by Owl. Owl can be reached at <a href="mailto:scholarships@scholarshipowl.com"><span><u>scholarships@scholarshipowl.com</u></a>, or at <span>{{ company_details()->getCompanyName() }}</span>, <span>{{ company_details()->getAddress1() }}</span></span>.</p>
            <p>Owl is not affiliated with, sponsored by, or endorsed by any School. Signing up, registering, or enrolling in a School does not increase your chances of winning.</p>
            <p><strong><u>Update History</u></strong></p>
            <div style="overflow: hidden;">
                <p style="float: left; width: 25%;"><strong>September 2019</strong></p>
                <p style="float: left; width: 75%;"><strong>Revised provision related to billing.</strong></p>
            </div>
            <div style="overflow: hidden;">
                <p style="float: left; width: 25%;"><strong>March 2018 </strong></p>
                <p style="float: left; width: 75%;"><strong> Revised terms and conditions.</strong></p>
            </div>
            <div style="overflow: hidden;">
                <p style="float: left; width: 25%;"><strong>November 2017</strong></p>
                <p style="float: left; width: 75%;"><strong>Revised provisions related to fees & billing, cancellation, proprietary rights and sweepstakes.</strong></p>
            </div>
            <div style="overflow: hidden;">
                <p style="float: left; width: 25%;"><strong>June 2017</strong></p>
                <p style="float: left; width: 75%;"><strong>Terms of Use created.</strong></p>
            </div>
          </div>
        </div>
      </div>
  </div>

@include('includes/refer')
@stop
