apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: engage.scholarship.app
  namespace: sunrise-mautic
spec:
  secretName: engage.scholarship.app
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
    - engage.scholarship.app
  acme:
    config:
    - dns01:
         provider: stage-dns
      domains:
      - engage.scholarship.app