apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: grafana
type: Opaque
data:
  GF_AUTH_GOOGLE_CLIENT_ID: NjI5OTA1MTQxMDctcXZyOWlqamlzMThxY2pycWQybmVnZGk1bjZnYjBtcTkuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  GF_AUTH_GOOGLE_CLIENT_SECRET: WTRFaDZzQnhmcXQ1alFSMmFkSHdMYTI4
  GF_SMTP_PASSWORD: Mzc3MWU0ZjEwMWI2MTJiZjQ4ZTVjNTIwZGYwM2VjZTljMDhmOTViZg==
  GF_SECURITY_ADMIN_USER: RGFlbHVyYXZlaW5pZTZ0aGluZWk0UHVuZw==
  GF_SECURITY_ADMIN_PASSWORD: ZXdXSmk3ZnI8PERCZGRYfVNpVSM2Q09YXFF9eCgp