kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-cert-manager-service-account
subjects:
  - kind: ServiceAccount
    namespace: kube-cert
    name: kube-cert-manager
roleRef:
  kind: ClusterRole
  name: kube-cert-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io