apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sowl-tech-prod-prometheus-cert
  namespace: monitoring
spec:
  secretName: prometheus.scholarshipowl.com
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
  - prometheus.scholarshipowl.com
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - prometheus.scholarshipowl.com