FROM php:7.2.27-fpm-stretch
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -yq install gnupg2 curl bash
RUN echo 'deb http://s3-eu-west-1.amazonaws.com/tideways/packages debian main' > /etc/apt/sources.list.d/tideways.list && \
    curl -sS 'https://s3-eu-west-1.amazonaws.com/tideways/packages/EEB5E8F4.gpg' | apt-key add - && \
    apt-get update && \
    apt-get -yq install tideways-php && \
    apt-get autoremove --assume-yes && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN install-php-extensions gd memcached redis zip pdo_mysql opcache intl mysqli mcrypt && php -m
ADD docker.conf /usr/local/etc/php-fpm.d/docker.conf
#RUN echo 'extension=tideways.so\ntideways.connection=tcp://tideways:9135\ntideways.api_key=KEY' > /usr/local/etc/php/conf.d/40-tideways.ini