apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sowl-tech-prometheus-cert
  namespace: monitoring
spec:
  secretName: sowl-tech.prometheus.scholarshipowl.tech.tls
  issuerRef:
    name: sowl-tech-prod
    kind: ClusterIssuer
  dnsNames:
  - sowl-tech.prometheus.scholarshipowl.tech
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - sowl-tech.prometheus.scholarshipowl.tech