# Default values for sunrise-mautic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
app: sowl-mautic

mautic:
  version: "2.14.2"
  sha1: "d896eb2389047509c841d8478191234bea432e44"

updateStrategy:
  type: RollingUpdate

livenessProbe:
  exec:
    command:
    - cat
    - /var/www/html/healthy
  initialDelaySeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5
readinessProbe:
  exec:
    command:
    - cat
    - /var/www/html/healthy
  initialDelaySeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

image:
  tag: 2.14.2
  repository: gcr.io/sowl-tech/sunrise-mautic/mautic
  pullPolicy: Always

service:
  name: mautic-port
  type: NodePort
  externalPort: 8080
  internalPort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts:
    - mautic.scholarshipowl.tech
  tls:
  - secretName: mautic.scholarshipowl.tech
    hosts:
      - mautic.scholarshipowl.tech

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
   cpu: 50m
   memory: 1000Mi


tolerations: []

affinity: {}



